### ISSUE TITLE
Time entry description distinction in result

### ISSUE THREAD

**Issue by JamesNZL** [JamesNZL/flow-toggl-plugin#117]
Feature request from @tdnzr in #116:

> Command clarity: I wish the text in the FlowLauncher suggestions clearly separated the command text from the task description, e.g. via different text colors or brackets or something. E.g. instead of "Start take a walk now", it would be "Start 'take a walk' now" or "Start [take a walk] now" or similar. See [this](https://i.imgur.com/KnjC3A1.png) screenshot.

**Comment by JamesNZL** [comment]
> I vaguely remember playing around with something like this (possibly Result.TitleHighlightData in the [API docs](https://www.flowlauncher.com/docs/#/API-Reference/Flow.Launcher.Plugin/Result)?) but IIRC it was either sketchy/ugly/deprecated/otherwise undesirable.

![image](https://github.com/JamesNZL/flow-toggl-plugin/assets/44986932/61b1ef03-5b65-41d5-8e11-f903bb5b83be)

Ah, I wasn't constructing—_subtitle_ highlighting was indeed deprecated.

![image](https://github.com/JamesNZL/flow-toggl-plugin/assets/44986932/690be947-0a34-4dc8-a86e-e6940464216e)
![image](https://github.com/JamesNZL/flow-toggl-plugin/assets/44986932/1d1c7f9c-8117-4d7b-9e98-99cfc5ea1ea7)

This highlighting uses the same colour as the fuzzy search match in the main search bar... seems to be decent?

![image](https://github.com/JamesNZL/flow-toggl-plugin/assets/44986932/df9f9c50-8f2a-4a0f-88f4-dca9c40e24b2)

Here is the alternative... I think I'll just impl the highlighting and leave it at that, no need for a toggle either I reckon.

@tdnzr

**Comment by JamesNZL** [comment]
![image](https://github.com/JamesNZL/flow-toggl-plugin/assets/44986932/a24cb81b-4a31-436f-841c-8afe81b3a3a4)
![image](https://github.com/JamesNZL/flow-toggl-plugin/assets/44986932/66c10af0-a809-4582-af03-a13946ef5ddc)
![image](https://github.com/JamesNZL/flow-toggl-plugin/assets/44986932/efa8cfc6-ea41-4d5c-ad8a-73072f3163f3)

**Comment by tdnzr** [comment]
That looks and works great, thanks. The highlight color even adapts to the FlowLauncher theme <3.

That concludes my Github issues & feedback on this project!

I wish you the best of luck with your future endeavours, whichever those are :).

PS: I made a tiny readme-related pull request #118.

**Comment by JamesNZL** [comment]
Happy to hear!

Thank you for all your comprehensive feedback & suggestions towards this, your command flow in particular made a massive difference to this plugin's overall usability.

and thank you for the well wishes, right back at you!
