### ISSUE TITLE
The "start" command is a bit unintuitive.

### ISSUE THREAD

**Issue by tdnzr** [JamesNZL/flow-toggl-plugin#27]
*Wow* this plugin is impressive.

I was, however, briefly confused how the "start" command worked. Here's why I was confused:

Example: I have a "take a walk" time entry in the "Exercise" project, and wanted to start the "take a walk" time entry.
-> I typed "tgl start take a walk" -> Enter -> That didn't work.
-> I typed "tgl start Exercise" -> Enter -> Now there was a "Start now" option, but I still didn't see how to start my "take a walk" entry. And pressing Enter again just started an untitled Exercise project. (Is that a common desirable use case?)

The actual solution is "tgl start Exercise" -> Enter -> "take a walk" (the full command here, however, is somehow "tgl start Exercise take a walk") -> Enter.

Perhaps you can see how that might be unintuitive to a new user^^.

---

I don't have a great suggestion for how to make this more intuitive. Maybe this command warrants some tutorialisation in the Readme, or some different presentation inside FlowLauncher in the step after one has selected a project (i.e. after "tgl start Exercise" -> Enter).

**Comment by JamesNZL** [comment]
Thank you for the feedback!

This week is *busy* (2 tests and 2 assignments/projects in the next 4 days), but I'll be sure to take another look at your issues soon.

**Comment by JamesNZL** [comment]
@tdnzr thank you again for the detailed suggestions and feedback, really appreciate your input!

> I typed "tgl start Exercise" -> Enter -> Now there was a "Start now" option, but I still didn't see how to start my "take a walk" entry. And pressing Enter again just started an untitled Exercise project. (Is that a common desirable use case?)

That is a valid point; I suppose it isn't the most intuitive if you haven't yet used the plugin.

Regarding whether creating untitled entries is common—I find myself indeed using it occasionally if I can't yet think of a good description for what I'm about to start doing.
Further, I want to keep parity with Toggl—they let you create unnamed time entries, so I'd like to allow the same.

> some tutorialisation in the Readme

This could work, but only for those users that actually check plugin repositories—normal users that are just browsing the `Plugin Store` wouldn't come across this, and I'd suggest that this would be the majority of users.

> some different presentation inside FlowLauncher in the step after one has selected a project

This might be the play—I'll try adding another `Usage Tip` result while the description is empty to remind the user to keep typing if they wish to name their time entry.

**Comment by tdnzr** [comment]
Hi there, thanks for the reply :).

> Regarding whether creating untitled entries is common—I find myself indeed using it occasionally if I can't yet think of a good description for what I'm about to start doing.
Further, I want to keep parity with Toggl—they let you create unnamed time entries, so I'd like to allow the same.

Yeah, I understand - I occasionally create unnamed time entries myself. I was mainly wondering if this specific use case, where you're sure enough about what you're tracking that you can already select a project, but not yet sure enough to name it, is common enough to warrant it being the "default" action when starting a time entry. If that action is rare enough, one could maybe restructure the "start" keyword so that the default action is choosing project plus time entry name. Whereas an unnamed time entry would be a special action, rather than the default one. But I can't quite envision how that might look like.

---

Re: the Usage Tip: That sounds like a decent solution. I had another idea, but don't know what options you have when developing plugins: is it possible to intentionally give the gray command hints, like the "start" in [this screenshot](https://i.imgur.com/Do7r0oH.png)? If so, you could add a gray hint of the form "Name your time entry" or whichever phrasing seemed suitable.

**Comment by JamesNZL** [comment]
> don't know what options you have when developing plugins: is it possible to intentionally give the gray command hints, like the "start" in [this screenshot](https://i.imgur.com/Do7r0oH.png)?

I had the same thought the other day—but I don't believe so.

I haven't been able to find any documentation on what sets that hint, and there is no code difference between those results (eg `tgl start`) and other results which provide no hints.

I'll ask on the Flow Discord server though, and see if there's something undocumented/that I've missed. 🙂

**Comment by JamesNZL** [comment]
> I haven't been able to find any documentation on what sets that hint, and there is no code difference between those results (eg tgl start) and other results which provide no hints.
> 
> I'll ask on the Flow Discord server though, and see if there's something undocumented/that I've missed. 🙂

Yeah, this isn't currently possible unfortunately.

This will roll out in the next release:

![image](https://github.com/JamesNZL/flow-toggl-plugin/assets/44986932/9d8961ae-d803-47ef-aa8d-59e18d1e0674)
