### ISSUE TITLE
Add plugin settings to disable and/or manage notifications

### ISSUE THREAD

**Issue by tdnzr** [JamesNZL/flow-toggl-plugin#31]
In Windows 11, any time I start a new time entry via the TogglTrack plugin, FlowLauncher spawns a Windows 11 notification.

From what I understand, the OS can only manage notifications in general, like disabling sound for *all* FlowLauncher notifications, but not for specific plugins. So it's unfortunate that the TogglTrack plugin spawns a notification whenever I start a new time entry. Including a notification sound, because I've enabled sounds in case FlowLauncher e.g. spawns an error notification.

-> Please let me disable the TogglTrack notifications entirely in the plugin settings, and/or allow finer-grained control. Like a setting to let TogglTrack error notifications through, while suppressing standard notifications that just confirm what I already know, like that I've just started a new time entry.

**Comment by JamesNZL** [comment]
Absolutely fair.

I'll add a setting in the next release to `allow all notifications`, `only error notifications`, or `block all notifications`.

**Comment by JamesNZL** [comment]
![image](https://github.com/JamesNZL/flow-toggl-plugin/assets/44986932/57b7be84-19a3-42a8-9c4d-53d878710b63)
